### ISSUE TITLE
Duplicate Games/Decks

### ISSUE THREAD

**Issue by Harrock** [Epix37/Hearthstone-Deck-Tracker#1323]
On the wins-losses the number is inaccurate. I went from 117 wins to 142 wins after one game which I lost. How can I fix it?

**Comment by Epix37** [comment]
Do you have any display filters set? https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#im-getting-no-stats-displayed-on-the-deck-list-screen-even-though-i-have-games-recorded

**Comment by Harrock** [comment]
I had the versions on Selected instead of all. Once I changed that I have won 164 games now.

**Comment by Epix37** [comment]
Do you see any oddities in `STATS > GAMES & STATISTICS > OVERALL > GAMES`? Please post a screenshot if you do.

**Comment by Harrock** [comment]
![hdt stats capture](https://cloud.githubusercontent.com/assets/8322685/9474203/317d4bec-4b2d-11e5-9521-461a50079968.PNG)

**Comment by Harrock** [comment]
I just started playing paladin and have online won 60 games.

**Comment by Harrock** [comment]
only - not online

**Comment by Epix37** [comment]
Please check the games in `overall > games`. 

Did you sync with hearthstats?

**Comment by Harrock** [comment]
I keep getting errors on the sync. Where is overall > games?

**Comment by Epix37** [comment]
I think the hearthstats servers went down for a bit earlier. 

In the screenshot above, the grey text on the left.

**Comment by Harrock** [comment]
My settings are good. I made a new priest deck and the stats are working fine.

**Comment by Epix37** [comment]
This seems to be an issue related to the recent hearthstats server issues. (HDT sending duplicates of matches/decks because it never got a response). As all of the duplicates should have the exact same length, opponent name, etc, etc, I should be able to remove all of them with an update soon.

**Comment by Epix37** [comment]
Found the problem, HDT-side fix is almost done, should be out tomorrow!

**Comment by Epix37** [comment]
v0.10.14 fixes this.

**Comment by YvesW** [comment]
After I fixed it and removed around 240 matches, the following popup keeps coming up when I start the tracker.
![1](https://cloud.githubusercontent.com/assets/7929021/9485661/27f35c2a-4bbd-11e5-975b-416efe491b02.PNG)
After clicking 'fix now', the tracker supposedly fixes it, but when I restart the tracker, I get the same popup. Should I just press don't fix?
![2](https://cloud.githubusercontent.com/assets/7929021/9485696/8eeabe8c-4bbd-11e5-8fc1-338a407b78bb.PNG)
![3](https://cloud.githubusercontent.com/assets/7929021/9485697/91127614-4bbd-11e5-86c8-cae4378e979f.PNG)
![4](https://cloud.githubusercontent.com/assets/7929021/9485701/93d6b75c-4bbd-11e5-98f3-bff0f6a8b080.PNG)
![5](https://cloud.githubusercontent.com/assets/7929021/9485702/95b36872-4bbd-11e5-89bf-aabc07924bfb.PNG)
They might be stats from a deleted deck or perhaps from a time when HDT didn't record the deck names or something like that. I guess the algorithm to detect duplicates fucks up somewhere (since I don't think those are really duplicate matches, not sure though), but I'm not sure why I keep getting the popup; they should have been deleted.

**Comment by Epix37** [comment]
I would suggest you just press don't fix, yea. 

Alternatively/additonaly, you could send me your files so I can have a look at the problem.
- options > tracker > backups
- create new
- show backup directory
- email the file called something like "BackupManual_25082015.zip" to epikz37@gmail.com

**Comment by MechaLynx** [comment]
Not sure if this is relevant. I don't use Hearthstats at all, never synced or anything, but I still got the duplicates report:

![dialog box](http://i.imgur.com/Fcckv9d.png)

I told HDT to delete them and I didn't get the popup again, so all seems to be fine. I don't care if they where mis-matches, but this may be relevant if only sync-related duplicates where the target. Only 1 of them seems to be in the last 2 months, so it may be unrelated to Hearthstone lag, or I get it more often than others.

**Comment by GiggliG** [comment]
Is there a way to be sure these games are duplicates, or false positives?

I am getting duplicates listed for games which have different dates. For example, look at top duplicate below:
![image](https://cloud.githubusercontent.com/assets/10089419/9494152/5e03f89e-4bfc-11e5-999c-27afeb6b3a6d.png)

The first game and its duplicates have the same duration, but use different versions of the deck, and the replay (old style) shows different games.

It seems like older games before HDT tracker recorded rank or opponent names produce a LOT of false positives. I have no confidence that any of the games shown in the dialog are actually duplicates because of this.

Since it's showing me ~200 duplicates, and all of them are checked by default, I cant use this feature. I need them to be unchecked by default, so I can go through, check a few, click delete selected, then come back to it later to work through the rest when i have time.

Also, this feature should probably be added to a menu item, so that it isn't popping up at every launch of HDT.

Finally, I'd suggest having the ability to click "this is not a duplicate" on games in the list, so it doesn't keep flagging them as duplicates later.

**Comment by Epix37** [comment]
Let me know you still have issues with this one: https://github.com/Epix37/HDT-Test/releases/tag/v0.10.15PRE1

**Comment by GiggliG** [comment]
That worked great! It only found 2 duplicates, which really were duplicates, and the dialog didn't pop up on next launch.

Great work.

**Comment by Epix37** [comment]
Perfect :).

**Comment by Epix37** [comment]
Pushed that to live. Should hopefully be good now.
