### ISSUE TITLE
How do I completely uninstall this program

### ISSUE THREAD

**Issue by Wieners** [Epix37/Hearthstone-Deck-Tracker#889]
I've played hearthstone since the second wave of closed beta and it's been fine until I downloaded this program. This program has given me nothing but problems. Whenever I do anything in game my fps just drops to zero for 2-4 seconds. Navigating menus, playing cards, watching opponent play cards, spectating a friend. I've played the game on either high or low since beta and they've both worked smoothly but changing them doesn't help anything either. It's infuriating and I need it off my computer NOW. I tried just deleting the zip and the unzipped folders and deleting from my recycle bin, repairing hearthstone, reinstalling the program to see if hearthstone would at least work with it on in the background. I don't know what this program does to the actual game, but this guy seems to have the same problem as well (http://eu.battle.net/hearthstone/en/forum/topic/14213341209)

I'm about ready to just reinstall hearthstone to see if that does anything because this is ridiculous that this one program could just destroy my entire game.

EDIT: I reinstalled hearthstone and nothing has changed.

**Comment by culinko** [comment]
I really doubt HS deck tracker caused any issues in this case. If you exit deck tracker and your problems still remain, it's not a fault of deck tracker, since the only thing it does is read the Hearthstone log. If you want to remove the deck tracker, just delete the unzipped folder and the app data folder (C:\Users\...\AppData\Roaming\HearthstoneDeckTracker).

As for the link you provided, it's absolutely irrelevant, because quoting the guy: " I scanned my system with Avast (founding tons of viruses, which got deleted/quatantined), I did even cleared my registry + used anti malware programs, which also found keysloggers and malicious files." This just blows my mind.

**Comment by FenrisWolffe** [comment]
Defrag your hard drive. Scan your disk with an anti-virus. Reboot in safe mode and do the same.

It's not this tiny little program. Especially if you run HS without the tracker, and still have the issues. Aggression is not warranted here.

**Comment by Wieners** [comment]
@culinko I linked that dude because I wouldn't be surprised if his game stopped working because of this program moreso than the keyloggers and viruses.

@FenrisWolffe Why is it then that I've only started having problems with hearthstone after downloading this program. It has to have done SOMEthing. There is absolutely zero reason for my hearthstone to just randomly stop working after playing since like August 20th 2013. The only thing that I've recently done that is hearthstone related besides playing this game is get this program. Is that really a coincidence that my game would stop working at the same time? I should be able to play without problems like I have without this program running or even on my computer anymore yes? And I don't think you know what aggression is if that's what you're labeling my post as.

**Comment by culinko** [comment]
I'm sure he didn't mean aggression in general, just that if you really seek help, your posts shouldn't be passive aggressive.

"I wouldn't be surprised if his game stopped working because of this program moreso than the keyloggers and viruses."

Are you really suggesting that viruses and keyloggers are less harmul than hs deck tracker? I really wanted to help you with the issues you've having, but unfortunately, you're crazy.

**Comment by Wieners** [comment]
@culinko I'm very skeptical that it's the viruses and keyloggers when his game sounds like it's doing the same things as mine and we downloaded the same program and both had problems with hearthstone at pretty much the same time after downloading it. And the fact that he scanned and cleaned his computer and still has problems? Seems sketchy.

And yes, the fact that you can get viruses and keyloggers (that get fixed by a simple scan & clean) that will do nothing to hearthstone, but apparently since I downloaded this program I can no longer play... I would have to say that this program was more harmful to my computer.

But who knows, maybe it's not the program. I'm very skeptical that it isn't. If you think you can help go for it.

**Comment by culinko** [comment]
"And the fact that he scanned and cleaned his computer and still has problems? Seems sketchy."

Even if you remove malware and viruses, many times the damage they've done is unrecoverable (broken registry, missing/corrupted dll files, missing exe files, all sorts of stuff).

"And yes, the fact that you can get viruses and keyloggers (that get fixed by a simple scan & clean) that will do nothing to hearthstone"

You have no idea how viruses work, I advise you read some pages on wikipedia. As I said earlier, even if you clean your system, it still can be very much corrupted.

The only thing this tracker does is read the hearthstone log. The tracker is open source, you can view all of its code here. As I told you in my previous post, if problems persist even if you close the tracker, the problem is not caused by tracker.

**Comment by Wieners** [comment]
@culinko "As I told you in my previous post, if problems persist even if you close the tracker, the problem is not caused by tracker." Do you realize how frustrating this is to hear when I've played fine for literal years until the day I put this program on my computer? It's unfathomable that it isn't something this program has done. All I want to do is remove any trace of this program and pray that it's fixed afterwards.

**Comment by FenrisWolffe** [comment]
The files should be under Username/Appdata/Roaming/HearthstoneDeckTracker if you have them installed there as default, and the program will be where-ever you installed it. Those are the sum total of this applications footprints on your system.

**Comment by Wieners** [comment]
@FenrisWolffe I've done this and it's still chugging. I don't know what to do.

**Comment by Epix37** [comment]
One very unlikely thing i can think of: HDT enables Hearthstone logging. Maybe, for some reason your machine can not handle that? I have never heard anyone having that issue before, but who knows. Close Hearthstone, go to "%LocalAppData%/Blizzard/Hearthstone" and delete the "log.config" file (I would recommend not touching any of the others in there). See if the problems persist.

**Comment by Wieners** [comment]
@Epix37 Oh my god that fixed it. It's running smoothly again now. My computer is from 2008 and hasn't changed much besides me upgrading the ram from 4gb to 8, so it probably just sucks too hard to use it. Thanks a bunch though.

**Comment by culinko** [comment]
Glad that Epix37 managed to help you with the issue. I was wrong about tracker not being the culprit, I didn't know hearthstone has not enabled logging by default. My apologies.

**Comment by Epix37** [comment]
Idk, I did not really expect that to help. Possibly a too slow HDD?

Good thing it's working again though. Enjoy your smoothly running game :).

**Comment by nylomatic** [comment]
Just wanted to let you know that I had this issue as well until I deleted the log.config file. So I guess there is no way for me to use HDT without stuttering. Is there any workaround you know of by now? HDT is awesome and it would be a shame not to be able to use it.
